version: '3.8'

services:
  my-dogs-deserve-a-website:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '9000:9000'
    image: my-dogs-deserve-a-website:stable
    networks:
      - netwoofs

networks:
  netwoofs:
